name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-paths:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      path: ${{ steps.changes.outputs.path == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            path:
              - 'src/**'
              - '.github/**'
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [check-paths]
    if: needs.check-paths.outputs.path == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test